Repository AY2122S1-CS2113T-W12-4/tp, pull requests merged in 2021-10, with the labels that each got.

#61 Fix for the post merger issue
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.High, type.Bug

#64 Feat/find command
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High, severity.High

#76 Implement sort function to List Command
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, priority.High, type.Task

#78 Feature: Remove Items
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/ui/Ui.java
Labels: type.Story, priority.High

#80 Added JUnit testing for Parser class.
  src/test/java/seedu/parser/ParserTest.java
Labels: priority.High, severity.High, type.Task

#81 More JUnit Tests for Parser
  src/test/java/seedu/parser/ParserTest.java
Labels: priority.Medium

#82 Added notification printed when Fridget is ran and after exiting.
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.High

#83 Feature: Implemented ExpiryCommand with color display
  src/main/java/seedu/commands/ExpiringCommand.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#95 Update User Guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#93 Feat/update notification feature
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/ExpiringCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/NotificationCommand.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/ResetCommand.java
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/notification/Notification.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High, severity.High

#104 Add J Unit test for Storage
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/storage/StorageTest.java
Labels: priority.Medium

#101 Ensure remove commands only removes items that exist in Fridget
  build.gradle
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/storage/IngredientList.java
Labels: type.Enhancement, priority.Low

#112 Fix message after adding an already existing item
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Low

#115 Feat/assertions ingredient list
  src/main/java/seedu/storage/IngredientList.java
  src/test/java/seedu/storage/IngredientListTest.java
Labels: priority.High, type.Task

#120 Update link to jar file in UG
  docs/UserGuide.md
Labels: priority.High

#125 Add logger to storage
  docs/UserGuide.md
  src/main/java/seedu/storage/Storage.java
Labels: severity.Low

#133 Dg/list command
  docs/DeveloperGuide.md
  docs/umlDiagrams/AddSequence.puml
  docs/umlDiagrams/ListSequence.png
  docs/umlDiagrams/ListSequence.puml
Labels: priority.High, type.Task

#208 Feat: add sort function in shopping list
  src/main/java/seedu/commands/ShopListCommand.java
  src/main/java/seedu/commands/ShopResetCommand.java
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/storage/ShoppingList.java
Labels: priority.High, type.Task
