Repository AY2122S1-CS2113T-W12-4/tp, pull requests merged in 2021-11, with the labels that each got.

#210 Feat: add shop commands in UG
  docs/UserGuide.md
  src/main/java/seedu/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#212 Throws error when input greater than Integer.MAX_VALUE
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/ui/Ui.java
Labels: priority.Medium, type.Bug, severity.Low

#213 Fix bugs on DG and also typos within code
  docs/DeveloperGuide.md
  docs/umlDiagrams/NotificationSequence.puml
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/ui/Ui.java
Labels: priority.High

#216 Update message for invalid input in reset commands
  src/main/java/seedu/ui/Ui.java
Labels: priority.Medium

#215 Fix/feedback
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/parser/Parser.java
Labels: priority.High

#214 Fix/refactoring
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/pumlFiles/AddAndRemoveCommand.puml
  docs/pumlFiles/AddSequence.puml
  docs/pumlFiles/Architecture.puml
  docs/pumlFiles/Command.puml
  docs/pumlFiles/ExpiringSequence.puml
  docs/pumlFiles/FindSequence.puml
  docs/pumlFiles/HelpSequence.puml
  docs/pumlFiles/ListSequence.puml
  docs/pumlFiles/NotificationSequence.puml
  docs/pumlFiles/RemoveCommand.puml
  docs/pumlFiles/RemoveSequence.puml
  docs/pumlFiles/ResetSequence.puml
  docs/pumlFiles/ShopListSequence.puml
  docs/pumlFiles/ShopResetSequence.puml
  docs/pumlFiles/UserFeedbackLoop.puml
  docs/umlDiagrams/AddAndRemoveCommand.png
  docs/umlDiagrams/AddSequence.png
  docs/umlDiagrams/AddSequence.puml
  docs/umlDiagrams/Architecture.png
  docs/umlDiagrams/Command.png
  docs/umlDiagrams/ExpiringSequence.png
  docs/umlDiagrams/FindSequence.png
  docs/umlDiagrams/ListSequence.png
  docs/umlDiagrams/NotificationSequence.png
  docs/umlDiagrams/RemoveCommand.png
  docs/umlDiagrams/RemoveSequence.png
  docs/umlDiagrams/ResetSequence.png
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/ExpiringCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/NotificationCommand.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/ResetCommand.java
  src/main/java/seedu/commands/ShopListCommand.java
  src/main/java/seedu/commands/ShopResetCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/data/exception/FridgetException.java
  src/main/java/seedu/data/ingredient/Ingredient.java
  src/main/java/seedu/data/item/Item.java
  src/main/java/seedu/fridget/Fridget.java
  src/main/java/seedu/notification/Notification.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/IngredientList.java
  src/main/java/seedu/storage/ItemList.java
  src/main/java/seedu/storage/ShoppingList.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/ingredient/IngredientTest.java
  src/test/java/seedu/ingredient/ItemTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/storage/IngredientListTest.java
  src/test/java/seedu/storage/ItemListTest.java
  src/test/java/seedu/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#217 Update quick start numbering typo for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#218 Fix/date bugs
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#222 Update personal portfolio page
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/zonglun.md
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/NotificationCommand.java
  src/main/java/seedu/data/exception/FridgetException.java
  src/main/java/seedu/notification/Notification.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#225 Updated PPP
  docs/team/uosjapuelks.md
Labels: priority.High

#228 Update authorship
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/ExpiringCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/data/item/Item.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/ItemList.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/item/ItemTest.java
  src/test/java/seedu/storage/ItemListTest.java
  src/test/java/seedu/ui/UiTest.java
Labels: priority.High

#229 Fix: polish code base
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/BryanElmer.md
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/ResetCommand.java
  src/main/java/seedu/commands/ShopListCommand.java
  src/main/java/seedu/commands/ShopResetCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/storage/ShoppingList.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/storage/ShoppingListTest.java
  src/test/java/seedu/storage/StorageTest.java
Labels: priority.High

#237 Fix/shopping list feature in update command
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/storage/Storage.java
Labels: priority.High

#236 Docs guides
  docs/UserGuide.md
Labels: priority.High

#240 Feat: add storage class diagram
  docs/DeveloperGuide.md
  docs/pumlFiles/StorageClass.puml
  docs/team/BryanElmer.md
  docs/umlDiagrams/StorageClass.png
Labels: priority.High

#239 Add more parser class diagrams to DG
  docs/DeveloperGuide.md
  docs/pumlFiles/Command.puml
  docs/pumlFiles/FridgetToParser.puml
  docs/pumlFiles/ParserToCommand.puml
  docs/umlDiagrams/Command.png
  docs/umlDiagrams/FridgetToParser.png
  docs/umlDiagrams/ParserToCommand.png
  src/main/java/seedu/notification/Notification.java
Labels: priority.High

#242 Fix: update sequence diagrams
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/pumlFiles/HandleRemovalOfItemsSequence.puml
  docs/pumlFiles/HandleRemovalOfMultipleQuantitySequence.puml
  docs/pumlFiles/RemoveSequence.puml
  docs/pumlFiles/ResetSequence.puml
  docs/pumlFiles/ShopListSequence.puml
  docs/pumlFiles/ShopResetSequence.puml
  docs/pumlFiles/StorageClass.puml
  docs/pumlFiles/UpdateShopListSequence.puml
  docs/team/bryanelmer.md
  docs/umlDiagrams/HandleRemovalOfItems.png
  docs/umlDiagrams/HandleRemovalOfItemsSequence.png
  docs/umlDiagrams/HandleRemovalOfMultipleQuantity.png
  docs/umlDiagrams/HandleRemovalOfMultipleQuantitySequence.png
  docs/umlDiagrams/RemoveSequence.png
  docs/umlDiagrams/ResetSequence.png
  docs/umlDiagrams/ShopListSequence.png
  docs/umlDiagrams/ShopResetSequence.png
  docs/umlDiagrams/UpdateShopListSequence.png
Labels: priority.High

#243 Fix font size for class diagrams and sequence diagrams.
  docs/DeveloperGuide.md
  docs/pumlFiles/Command.puml
  docs/pumlFiles/FridgetInitialise.puml
  docs/pumlFiles/FridgetToParser.puml
  docs/pumlFiles/HelpSequence.puml
  docs/pumlFiles/NotificationSequence.puml
  docs/pumlFiles/ParserToCommand.puml
  docs/team/zonglun99.md
  docs/umlDiagrams/Command.png
  docs/umlDiagrams/FridgetInitialise.png
  docs/umlDiagrams/FridgetToParser.png
  docs/umlDiagrams/HelpSequence.png
  docs/umlDiagrams/NotificationSequence.png
  docs/umlDiagrams/ParserToCommand.png
Labels: priority.High

#244 Fix notification printing bug
  src/main/java/seedu/notification/Notification.java
Labels: priority.High, type.Bug

#248 Dg upgrade
  docs/pumlFiles/ExpiringSequence.puml
  docs/pumlFiles/FindSequence.puml
  docs/pumlFiles/ListSequence.puml
  docs/umlDiagrams/ExpiringSequence.png
  docs/umlDiagrams/FindSequence.png
  docs/umlDiagrams/ListSequence.png
  src/test/java/seedu/storage/ItemListTest.java
Labels: priority.High

#254 ItemList and ShoppingList
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#259 fix Developer guide index
  docs/DeveloperGuide.md
  docs/team/uosjapuelks.md
Labels: priority.High
